### ISSUE TITLE
Licensing paradox

### ISSUE THREAD

**Issue by ewancg** [WinampDesktop/winamp#10]
Your license gives off the impression that you want to piggyback off of the open source community and not give anything back. Not that it's illegal, but it *is* against the GitHub TOS (#6), and does defeat the entire purpose of even having the code published online.

If we can look past that for a moment. Say someone did want to contribute under your extremely prohibitive, nonfree license.
```
- Contribution to Project: You are encouraged to contribute improvements, enhancements, and bug fixes back to the project. Contributions must be submitted to the official repository and will be reviewed and incorporated at the discretion of the maintainers.
```
If you intend for users to contribute to this repository, doing so is not possible because of your own licensing terms, explicitly stating:
```
- No Forking: You may not create, maintain, or distribute a forked version of the software.
``` 
Creating a fork is necessary to contribute to any repository on GitHub unless the user has pre-existing collaborator rights and can push directly to the repository.

**Comment by jfmauguit** [comment]
duplicate

**Comment by ewancg** [comment]
Of?

**Comment by PEPSIMANTR** [comment]
> Of?

#6

**Comment by ewancg** [comment]
Hmm. I thought my language was pretty clear that this highlights a different issue

**Comment by PEPSIMANTR** [comment]
> Hmm. I thought my language was pretty clear that this highlights a different issue

Yeah, it was but more like repo owner didn't care.

**Comment by torrobinson** [comment]
> > Hmm. I thought my language was pretty clear that this highlights a different issue
> 
> Yeah, it was but more like repo owner didn't care.

Repo owner beefed it bigly

**Comment by ewancg** [comment]
Indeed
