### ISSUE TITLE
Winamp will not winamp

### ISSUE THREAD

**Issue by ArcZ9** [WinampDesktop/winamp#1043]
When I try to run winamp it will not winamp so I  cant winamp.

**Comment by thunderarchiv** [comment]
you just need to run winamp with the winamp compability layer applied (not an winamp emulator) and winamp will winamp as expected.

**Comment by ArcZ9** [comment]
> you just need to run winamp with the winamp compability layer applied (not an winamp emulator) and winamp will winamp as expected.

My winamp compatibility layer gave me a error that I am missing winamp to run the winamp compatibility layer with winamp runtime on my winamp os.

**Comment by arefdsg** [comment]
your winamp is too new

**Comment by ArcZ9** [comment]
> your winamp is too new

Ah damn you are right I was using winamp ver winamp rather than winamp ver winamp.

Problem solved.

**Comment by ArcZ9** [comment]
> your winamp is too new

ah yeah I was using winamp ver winamp rather than winamp ver winamp winamp.
