### ISSUE TITLE
Will WinAMP be rewritten in HolyC?

### ISSUE THREAD

**Issue by halal-beef** [WinampDesktop/winamp#1076]
![Terry_Davis_car.jpg](https://github.com/user-attachments/assets/b266fb02-f19a-4655-ba1d-7525a52db79f)

**Comment by vtomes** [comment]
WinTemple - God's favorite media player

**Comment by derula** [comment]
Please search the existing issues before opening a new one. This is already being tracked as #845.

**Comment by halal-beef** [comment]
ah right, my bad, looks like I missed that while looking thru issues

**Comment by tonytins** [comment]
HolyC, Batman!

**Comment by FullstackCypher1510** [comment]
Divine Intellect
