### ISSUE TITLE
A mess

### ISSUE THREAD

**Issue by gbillus** [WinampDesktop/winamp#1091]
Im not gonna lie... this is a mess. You have things uploaded that you don't have the license for, I saw something my brother wrote back in the day and it is not open source or licensed as such. Not a big deal on our end, the library is antiquated but I saw stuff from Google, Dolby, Microsoft and I believe IBM. This is a liability nightmare for your legal team. There is at least $150,000 in settlements here..... And be sure not just to delete the unlicensed code, but actually remove it from the repo, otherwise you are still distributing it. Also you should relicense under a real license. Clause 3, 5, and 6 are invalidated in the preamble and will not hold weight in court. As it stands, because of the conflicting terminology, it would be possible to redistribute WinAmp thru official channels without incurring any liability or damages. You need a supervisor, on site, STAT. You can close this after reading, I dont think im the one with an issue today.... Good Luck!

**Comment by soyneed** [comment]
> Im not gonna lie... this is a mess. You have things uploaded that you don't have the license for, I saw something my brother wrote back in the day and it is not open source or licensed as such. Not a big deal on our end, the library is antiquated but I saw stuff from Google, Dolby, Microsoft and I believe IBM. This is a liability nightmare for your legal team. There is at least $150,000 in settlements here..... And be sure not just to delete the unlicensed code, but actually remove it from the repo, otherwise you are still distributing it. Also you should relicense under a real license. Clause 3, 5, and 6 are invalidated in the preamble and will not hold weight in court. As it stands, because of the conflicting terminology, it would be possible to redistribute WinAmp thru official channels without incurring any liability or damages. You need a supervisor, on site, STAT. You can close this after reading, I dont think im the one with an issue today.... Good Luck!

![crying soyak](https://github.com/user-attachments/assets/d6e15172-d58c-4ba7-a235-636e9f052961)

**Comment by gbillus** [comment]
> [soyneed](/soyneed)

What? Are you butthurt that I didn't "tear them a new one" for using our code? I couldn't care less. Or is that a preview for your new profile pic? LOL! Literally, little bro, its not even worth getting up in arms about. It will eventually be straightened out. Its just funny to watch, but I wanted to at least make an attempt at being a good samaritan. Oh well, doesnt affect me one way or the other. See you all in h-
Florida!
