### ISSUE TITLE
tree includes source code for SHOUTcast DNAS 

### ISSUE THREAD

**Issue by nilsding** [WinampDesktop/winamp#11]
Hi,
in [/Src/Plugins/DSP/sc_serv3](https://github.com/WinampDesktop/winamp/tree/0695744fd658c42b372b7cb61584544c20e1c2ea/Src/Plugins/DSP/sc_serv3) is the source code of the SHOUTcast server software, which... [I guess nowadays requires a user or subscription to just even receive the binaries?](https://www.shoutcast.com/pricing/basic)  Not sure if this is supposed to be included here, but now its source code is just out there for all eternity...

Out of curiosity I built it on my main Linux machine that's running aarch64... had to adapt the `GNUmakefile` for that.  Since forking is forbidden, I will just paste the diff here:

```diff
commit 80659e1cbd497e65a7df610e119fbb7aa757e44f (HEAD -> community)
Author: Jyrki Gadinger <nilsding@nilsding.org>
Date:   Tue Sep 24 18:37:22 2024 +0200

    sc_serv3: add support for building on aarch64 linux

diff --git a/Src/Plugins/DSP/sc_serv3/GNUmakefile b/Src/Plugins/DSP/sc_serv3/GNUmakefile
index eebf3052..9cfb5028 100644
--- a/Src/Plugins/DSP/sc_serv3/GNUmakefile
+++ b/Src/Plugins/DSP/sc_serv3/GNUmakefile
@@ -8,6 +8,7 @@ x64 := $(shell uname -m)
 ENDIAN := $(shell uname -m)
 ENDIAN := $(patsubst i%86,LITTLE_ENDIAN,$(ENDIAN))
 ENDIAN := $(patsubst x86_64,LITTLE_ENDIAN,$(ENDIAN))
+ENDIAN := $(patsubst aarch64,LITTLE_ENDIAN,$(ENDIAN))
 ENDIAN := $(patsubst Power Macintosh,BIG_ENDIAN,$(ENDIAN))
 CXX=g++ -std=c++11 -Wno-deprecated
 
@@ -61,7 +62,7 @@ ifeq ($(OS),LINUX)
 
                ### Linux platform specific includes
                ### with 32-bit and 64-bit handling
-               ifeq ($(x64),x86_64)
+               ifeq ($(x64),$(filter $(x64),x86_64 aarch64))
                        INCLUDES=-Ideps/x86_64/include
                        PLATFORM_LIBS=\
                                -Ldeps/x86_64/lib -lexpat -lcurl -lssl -lcrypto -lpthread -lz -lrt -ldl
```

And well, building it worked, and running the server software worked too:

![Screenshot_20240924_183106](https://github.com/user-attachments/assets/3d53ac0f-c563-424e-8767-a4b6c4b4f495)

**Comment by jfmauguit** [comment]
Code removed, thanks for the report

**Comment by Architector4** [comment]
> [/Src/Plugins/DSP/sc_serv3](https://github.com/WinampDesktop/winamp/tree/0695744fd658c42b372b7cb61584544c20e1c2ea/Src/Plugins/DSP/sc_serv3)

HAHAHAHHHAAA AMAZING JOB

**Comment by nilsding** [comment]
@jfmauguit unfortunately, this is not how Git works.

You would need to rewrite the commit history and remove that directory from the commit that added it (e.g. via `git rebase --interactive`) from all the branches.  Right now people can simply revert the [code-deletion commit](https://github.com/WinampDesktop/winamp/commit/0a4b7d32d090696e5aab8de9c61dda9dab76aabf) using something like `git revert 0a4b7d32d090696e5aab8de9c61dda9dab76aabf`. 

GitHub has a guide about this, though I haven't tried the mentioned tools there: https://docs.github.com/en/authentication/keeping-your-account-and-data-secure/removing-sensitive-data-from-a-repository

**Comment by Architector4** [comment]
Anyway now that the [branch main was merged into community](https://github.com/WinampDesktop/winamp/commit/285c0f36958fbb889b78f369ac50d23f922fabef), undoing the commit that removed all this code from the branch, the codebase is back to having to the aforementioned proprietary code.

Reopen issue?

**Comment by Architector4** [comment]
Aw, ruined by Jef. Nevermind.

https://github.com/WinampDesktop/winamp/commit/1be04037cdba95396eef7728134043ba3ee6fbf4

**Comment by ihateradiohead** [comment]
peak

**Comment by offeex** [comment]
pcoc

**Comment by muesqtk** [comment]
lesgo

**Comment by Yotsubal** [comment]
Pirate at its peak

**Comment by Yotsubal** [comment]
Cant wait for lawsuit

**Comment by ki4arl** [comment]
Lmao

**Comment by li0ard** [comment]
lmao

**Comment by nitreojs** [comment]
i'd just recommend creating a PR with completed `.gitignore` file at this point

**Comment by arefdsg** [comment]
https://github.com/user-attachments/assets/e7eeae3a-2b73-480d-af8e-d25c991569f5

**Comment by akkez** [comment]
![image](https://github.com/user-attachments/assets/03ce4a7b-b3a6-4684-949c-25cd1fc867ad)

**Comment by yookoala** [comment]
Sadly, orphan commits are still available online. You can still download it if you know the right command (I'm not going to share, but it is not that difficult to find).

There is no command to force removing the orphan commit on remote git repository. What Nullsoft would want to do is to run garbage collection on their remote repository here, which I don't think normal GitHub user would have the permission to.

See: https://stackoverflow.com/a/3163451/372172

**Comment by ParzivalWolfram** [comment]
> i'd just recommend creating a PR with completed `.gitignore` file at this point

Remember: no forks!

**Comment by dj3520** [comment]
> Sadly, orphan commits are still available online. You can still download it if you know the right command (I'm not going to share, but it is not that difficult to find).

Funny enough you don't need a "command." Just decent competency at navigating the web interface.

**Comment by amirasyraf** [comment]
This is hilarious, it's like the winamp team has never used Git or any VCS before

**Comment by yookoala** [comment]
> This is hilarious, it's like the winamp team has never used Git or any VCS before

Cut them some slack.

[Winamp](https://en.wikipedia.org/wiki/Winamp) is a really old application. The initial release was 21th April 1997, predate [Linux](https://en.wikipedia.org/wiki/Linux)'s public release for a few months.

Distributed VCS was not a thing back in 1997. Even [BitKeeper](https://en.wikipedia.org/wiki/BitKeeper), the VCS that inspired Linus Torvalds to create git, was still 11 years away. Even [subversion](https://en.wikipedia.org/wiki/Apache_Subversion) needed 3 more years to release. Their choice in VCS was basically just CSV or similar commercial solution. And I'm sure anything from that age would work fine internally for many, many years.

git, created in 2005, was not a norm until recently. Let alone GitHub.

They can certainly do better in many aspects. And I wish they do.

**Comment by GurliGebis** [comment]
> > This is hilarious, it's like the winamp team has never used Git or any VCS before
> 
> Cut them some slack.
> 
> [Winamp](https://en.wikipedia.org/wiki/Winamp) is a really old application. The initial release was 21th April 1997, predate [Linux](https://en.wikipedia.org/wiki/Linux)'s public release for a few months.
> 
> Distributed VCS was not a thing back in 1997. Even [BitKeeper](https://en.wikipedia.org/wiki/BitKeeper), the commercial VCS that inspired Linus Torvalds to create git, was still 3 years away. Even [subversion](https://en.wikipedia.org/wiki/Apache_Subversion) needed 3 more years to release. Their choice in VCS was basically just CSV or similar commercial solution. And I'm sure anything from that age would work fine internally for many, many years.
> 
> git, created in 2005, was not a norm until recently. Let alone GitHub.
> 
> They can certainly do better in many aspects. And I wish they do.

With how people are acting, creating junk issues, I don't think they are getting closer to want to opensource it and work with the community.

My guess would be that they wake up, sees this mess and just decide that this was the wrong move, and remove it from github again.

My guess about the license choice is that it contains some code they have licensed, which they don't have permission to let other people use.

Unfortunately, I don't see people acting like small children helping - if anything, this might be used by others to say: "We don't want to try and opensource our old propritary software, look how people start acting"
So yes, the license is not optimal, but that can be fixed - the question is, do they want to, after this?

**Comment by yookoala** [comment]
> > > This is hilarious, it's like the winamp team has never used Git or any VCS before
> > 
> > 
> > Cut them some slack.
> > [Winamp](https://en.wikipedia.org/wiki/Winamp) is a really old application. The initial release was 21th April 1997, predate [Linux](https://en.wikipedia.org/wiki/Linux)'s public release for a few months.
> > Distributed VCS was not a thing back in 1997. Even [BitKeeper](https://en.wikipedia.org/wiki/BitKeeper), the commercial VCS that inspired Linus Torvalds to create git, was still 3 years away. Even [subversion](https://en.wikipedia.org/wiki/Apache_Subversion) needed 3 more years to release. Their choice in VCS was basically just CSV or similar commercial solution. And I'm sure anything from that age would work fine internally for many, many years.
> > git, created in 2005, was not a norm until recently. Let alone GitHub.
> > They can certainly do better in many aspects. And I wish they do.
> 
> With how people are acting, creating junk issues, I don't think they are getting closer to want to opensource it and work with the community.
> 
> My guess would be that they wake up, sees this mess and just decide that this was the wrong move, and remove it from github again.
> 
> My guess about the license choice is that it contains some code they have licensed, which they don't have permission to let other people use.
> 
> Unfortunately, I don't see people acting like small children helping - if anything, this might be used by others to say: "We don't want to try and opensource our old propritary software, look how people start acting" So yes, the license is not optimal, but that can be fixed - the question is, do they want to, after this?

No objection here. All valid point.

I can see how an old, conservative tech company hesitate to really open up their code base. Still no point for other developers to help a commercial product unconditionally. Let's see if this get better or worse.

**Comment by amirasyraf** [comment]
> > This is hilarious, it's like the winamp team has never used Git or any VCS before
> 
> Cut them some slack.
> 
> [Winamp](https://en.wikipedia.org/wiki/Winamp) is a really old application. The initial release was 21th April 1997, predate [Linux](https://en.wikipedia.org/wiki/Linux)'s public release for a few months.
> 
> Distributed VCS was not a thing back in 1997. Even [BitKeeper](https://en.wikipedia.org/wiki/BitKeeper), the commercial VCS that inspired Linus Torvalds to create git, was still 3 years away. Even [subversion](https://en.wikipedia.org/wiki/Apache_Subversion) needed 3 more years to release. Their choice in VCS was basically just CSV or similar commercial solution. And I'm sure anything from that age would work fine internally for many, many years.
> 
> git, created in 2005, was not a norm until recently. Let alone GitHub.
> 
> They can certainly do better in many aspects. And I wish they do.

Sorry I'm not sure how the date of winamp release is relevant. Are you saying the people working at winamp did not have access to newer tech since the release of their software all these years? As if they've been living in caves? They just stuck with what they had for more than 2 decades?

I don't agree with other people trolling creating junk issues and pull request, but I definitely don't agree with Winamp's approach here especially with their license. Not familiar with the open source scene isn't a valid excuse.

**Comment by GurliGebis** [comment]
I agree, and I hope they end we can have a constructive dialog with them, and end up with a usable license.
They might be unfamiliar with open source, and if that is the case, perhaps they should be helped in the right direction?

**Comment by johnLegasse** [comment]
> > This is hilarious, it's like the winamp team has never used Git or any VCS before
> 
> Cut them some slack.
> 
> [Winamp](https://en.wikipedia.org/wiki/Winamp) is a really old application. The initial release was 21th April 1997, predate [Linux](https://en.wikipedia.org/wiki/Linux)'s public release for a few months.
> 
> Distributed VCS was not a thing back in 1997. Even [BitKeeper](https://en.wikipedia.org/wiki/BitKeeper), the commercial VCS that inspired Linus Torvalds to create git, was still 3 years away. Even [subversion](https://en.wikipedia.org/wiki/Apache_Subversion) needed 3 more years to release. Their choice in VCS was basically just CSV or similar commercial solution. And I'm sure anything from that age would work fine internally for many, many years.
> 
> git, created in 2005, was not a norm until recently. Let alone GitHub.
> 
> They can certainly do better in many aspects. And I wish they do.

Irrelevant,
current company has nothing to do with the back then company: Nullsoft -> aol -> radionomy
The last one had 10y to setup a git, and no, its unlikely they were using diskette prior that

**Comment by NJdevPro** [comment]
> > This is hilarious, it's like the winamp team has never used Git or any VCS before
> 
> Cut them some slack.
> 
> [Winamp](https://en.wikipedia.org/wiki/Winamp) is a really old application. The initial release was 21th April 1997, predate [Linux](https://en.wikipedia.org/wiki/Linux)'s public release for a few months.
> 
> Distributed VCS was not a thing back in 1997. Even [BitKeeper](https://en.wikipedia.org/wiki/BitKeeper), the commercial VCS that inspired Linus Torvalds to create git, was still 3 years away. Even [subversion](https://en.wikipedia.org/wiki/Apache_Subversion) needed 3 more years to release. Their choice in VCS was basically just CSV or similar commercial solution. And I'm sure anything from that age would work fine internally for many, many years.
> 
> git, created in 2005, was not a norm until recently. Let alone GitHub.
> 
> They can certainly do better in many aspects. And I wish they do.

To be clear, the current Winamp team (the Llama group, based in Belgium) has _absolutely nothing_ to do with Nullsoft, who are the original developers. Winamp has been bought several times in between.

The original author and main dev of Winamp and SHOUTcast is Justin Frankel, who has an account on Github (JustinFrankel). He sold Winamp v2 to AOL in 1999 for a hefty sum of money. Then AOL continued the development, and the current owner bought v5.6 or 5.7 in 2014. Obviously, they did very little development on it.

Justin Frankel now runs the Cockos company, for which he and his associate develop the extremely awesome REAPER DAW. Pretty top of the shelf developers if you want my opinion. And of course they use git for that.

**Comment by davehodls** [comment]
Removing the code without rebasing doesn't completely obliterate the source, but it does reduce how often it will be noticed. From a business perspective, minimization of a potential problem is generally more acceptable than perfect protection from it. Considering anything this popular being posted will be essentially out there forever, the risk is low that someone will threaten the company with a Shoutcast knockoff based on the source code here, at least lower than having it still existing on the main branch.

**Comment by Architector4** [comment]
Eh, it's less about critique of how well they removed it, and more a notice for winamp peeps that this repository still actively redistributes it illegally. Making it slightly less available is good, but probably doesn't do much for a legal case in case they get sued or something lol
