### ISSUE TITLE
Удаляйте паблик

### ISSUE THREAD

**Issue by se7entomo** [WinampDesktop/winamp#1151]

**Comment by mrksbgg** [comment]
удаляю

**Comment by gohoski** [comment]
Удаляй на___ свой канал, пародийный б__ть

**Comment by se7entomo** [comment]
> Удаляй на___ свой канал, пародийный б__ть


1. Пародийный на что
2. Не мешай выражать недовольство лицухой винамп щитпостингом.
3. Есть иссуе и похуже
