### ISSUE TITLE
Google Pixel

### ISSUE THREAD

**Issue by kernel86-64** [WinampDesktop/winamp#1165]
Google Pixel is a brand of portable consumer electronics that run either ChromeOS or the stock version of the Android operating system. The main line of Pixel products consist of Android-powered smartphones, which have been produced since October 2016 as the replacement of the older Nexus, and of which the Pixel 9, Pixel 9 Pro and Pixel 9 Pro XL are the current models. The Pixel brand also includes laptop and tablet computers, as well as several accessories, and was originally introduced in February 2013 with the[Chromebook Pixel.

**Comment by nttttx** [comment]
GOOGLE P8XEL 6 PRO ЭТО ПОЛНОЕ ГАВНО ЗАЧЕМ ЖЕ Я ЕГО КУПИЛ КАКОЙ ЖЕ Я ТУПОЙ ДЕБИЛ
