### ISSUE TITLE
let people fork your crappy software

### ISSUE THREAD

**Issue by lime360** [WinampDesktop/winamp#1221]
like really, you need to simply allow forking your goddamn media player instead of just saying "NO FORKING OR WE WILL BREAK YOU KNEECPAS!?!?1/!?!?1/u@!w!i!wui@" because disallowing forking is against github's tos

besides, i think github will also use your code for their ai and you'll do nothing about it

just put any open-source license (or make it public domain) instead of just putting a proprietary license

**Comment by anoraktrend** [comment]
GPL could be the license to use.

**Comment by dark-steveneq** [comment]
Yes, GPL seems like a good license for this case. The only thing that would need to get implemented into the code or rather the build process to change branding included with the final build similar to how Mozilla does things with Firefox.

**Comment by lime360** [comment]
yeah lets go with gpl

**Comment by overanalytcl** [comment]
technically, they've removed the clause where it disallows you from forking, so you can do that rn

**Comment by lime360** [comment]
> technically, they've removed the clause where it disallows you from forking, so you can do that rn

that's what i did lol
