### ISSUE TITLE
ГОЙДА!

### ISSUE THREAD

**Issue by Nexeron1** [WinampDesktop/winamp#1233]
ЗДЕСЬ ЖЕ ЧЕРНЫМ ПО БЕЛОМУ НАПИСАНО! ГОЙДА!

**Comment by zxcwsurx** [comment]
Uploading VID_20240924_204104_917.mp4…

**Comment by zxcwsurx** [comment]
https://github.com/user-attachments/assets/053425d0-1030-4891-a968-f5013bab9929

**Comment by ilya-vysotsky-1** [comment]
донпть
