### ISSUE TITLE
Шаббат шалом, братья евреи!

### ISSUE THREAD

**Issue by kuraysdev** [WinampDesktop/winamp#1293]
@C6OI @Assasans @keneshindev @Luminate-D

**Comment by Luminate-D** [comment]
шаббат шалом шамы ашыден кигиы

**Comment by C6OI** [comment]
<img src="https://files.c6oi.ru/api/public/dl/h1M2UnWg/%D0%BF%D0%B0%D0%BF%D0%B8%D1%87-papich.gif">

**Comment by C6OI** [comment]
шалом

**Comment by ilya-vysotsky-1** [comment]
донатьте

**Comment by kuraysdev** [comment]
> донатьте

шекелей нет донать сам

**Comment by sdzkHelince** [comment]
шалом
