### ISSUE TITLE
Скиньте тон на abramovegor.ton пжпж

### ISSUE THREAD

**Issue by kuraysdev** [WinampDesktop/winamp#1294]

**Comment by ilya-vysotsky-1** [comment]
сначала задонать мне, мохову

**Comment by kuraysdev** [comment]
> сначала задонать мне, мохову

а куда тебе донатить

**Comment by ilya-vysotsky-1** [comment]
> > сначала задонать мне, мохову
> 
> а куда тебе донатить
страница donate видала ошiбку поэтому кiну номер 88005553555
