### ISSUE TITLE
Snow leopard

### ISSUE THREAD

**Issue by 000yesnt** [WinampDesktop/winamp#1307]
![IMG_20240924_015046_389](https://github.com/user-attachments/assets/208a143a-e0f1-4be6-bde0-247481e25386)

**Comment by C6OI** [comment]
# MEOW

**Comment by C6OI** [comment]
THANK YOU FOR THE AVATAR 
![image](https://github.com/user-attachments/assets/7f11521e-3f73-41e1-b910-48020e51b92d)
