### ISSUE TITLE
Winamp is de facto licensed under the GPL. Stop protecting a greedy corporation.

### ISSUE THREAD

**Issue by MichaelAgarkov** [WinampDesktop/winamp#1590]
GPLv3, section 7

```
If the Program as you
received it, or any part of it, contains a notice stating that it is
governed by this License along with a term that is a further
restriction, you may remove that term.
```

I'm tired of all the people here who aren't competent enough and don't even read the GPL while complaining about it.

_Originally posted by @MichaelAgarkov in https://github.com/WinampDesktop/winamp/issues/265#issuecomment-2379508779_

**Comment by LennyMcLennington** [comment]
@MichaelAgarkov this clause does not mean what you interpret it as, but in any case there is no GPLv3 violation. The purported violation was a violation of GPLv2. This goes to show that you people don't even know what you are arguing about.

**Comment by eversiege** [comment]
Still, the No Forking clause is illegal in EU and some countries and GitHub's ToS, so that could be the main problem for them than a GPL violation

**Comment by Trolldemorted** [comment]
@MichaelAgarkov even if we ignore your confusion of GPL 2 and 3, the cited sentence is about "the program" (which is licensed under the GPL, so in this case a dependency), not "covered work" (winamp).

**Comment by MichaelAgarkov** [comment]
> @MichaelAgarkov even if we ignore your confusion of GPL 2 and 3, the cited sentence is about "the program" (which is licensed under the GPL, so in this case a dependency), not "covered work" (winamp).

Isn't Winamp build around those libraries? Especially considering they **were** modified.

**Comment by Trolldemorted** [comment]
@MichaelAgarkov Winamp being built around those libraries makes it "covered work", not "the program". You probably can take the modifications of the libraries as GPLv2 (due to section 7), but not Winamp.

If a GPLv2 dependency author considers Winamp a "covered work" (which it probably is), they can go to court and demand Winamap to be released under GPLv2. But until a court has decided that or the Winamp authors change the license w/o a lawsuit, Winamp is not GPLv2.

**Comment by LennyMcLennington** [comment]
BTW for reference the rough equivalent to GPLv3's term "covered work" in GPLv2 is "work based on the Program", in case people wanted to actually read the relevant parts of the CORRECT license.

**Comment by MichaelAgarkov** [comment]
> @MichaelAgarkov Winamp being built around those libraries makes it "covered work", not "the program". You probably can take the modifications of the libraries as GPLv2 (due to section 7), but not Winamp.
> 
> If a GPLv2 dependency author considers Winamp a "covered work" (which it probably is), they can go to court and demand Winamap to be released under GPLv2. But until a court has decided that or the Winamp authors change the license w/o a lawsuit, Winamp is not GPLv2.

I see, then my fault.

**Comment by LennyMcLennington** [comment]
@MichaelAgarkov Please delete this issue or edit the title and body to make it clear that it is misinformation.
