### ISSUE TITLE
Please clean out unnecessary issues

### ISSUE THREAD

**Issue by ryanthomas-org** [WinampDesktop/winamp#1605]
The issues here are full of completely unnecessary posts; please clean them out 

EDIT:

For anyone down-voting this, I'll have you know I graduated top of my class in the Navy Seals, and I've been involved in numerous secret raids on Al-Qaeda, and I have over 300 confirmed kills. I am trained in gorilla warfare and I'm the top sniper in the entire US armed forces. You are nothing to me but just another target. I will wipe you out with precision the likes of which has never been seen before on this Earth, mark my words. You think you can get away with this? Think again. 

As we speak I am contacting my secret network of spies across the USA and your IPs are being traced right now so you better prepare for the storm. The storm that wipes out the pathetic little thing you call your life. I can be anywhere, anytime, and I can take you down in over seven hundred ways, and that's just with my bare hands. Not only am I extensively trained in unarmed combat, but I have access to the entire arsenal of the United States Marine Corps and I will use it to its full extent to wipe your miserable asses off the face of the continent. You're done.

**Comment by ArcZ9** [comment]
> Not only am I extensively trained in unarmed combat, but I have access to the entire arsenal of the United States Marine Corps and I will use it to its full extent to wipe your miserable asses off the face of the continent. You're done.

DO IT I DARE YOU DO IT DO IT DO IT.

I WANT US MARINES ATTACK ME TO PROTECT WINAMP ! 

![bbd7c3a6e9084d28ce0da3f3ec69755d-1501361034](https://github.com/user-attachments/assets/301d4cf5-fb48-4f1d-9415-094dd0c24a7c)

**Comment by mark-ass-brownlee-confirmed** [comment]
@ryanthomas-org and your [entire blog](https://ryanthomas.org/) is an unnecessary post. Your life may as well be unnecessary too. What is very necessary on the other hand is my app, which you can check out at [panels.art](https://panels.art)! - Markass Brownlee

**Comment by Vukis69** [comment]
> The issues here are full of completely unnecessary posts; please clean them out
> 
> EDIT:
> 
> For anyone down-voting this, I'll have you know I graduated top of my class in the Navy Seals, and I've been involved in numerous secret raids on Al-Qaeda, and I have over 300 confirmed kills. I am trained in gorilla warfare and I'm the top sniper in the entire US armed forces. You are nothing to me but just another target. I will wipe you out with precision the likes of which has never been seen before on this Earth, mark my words. You think you can get away with this? Think again.
> 
> As we speak I am contacting my secret network of spies across the USA and your IPs are being traced right now so you better prepare for the storm. The storm that wipes out the pathetic little thing you call your life. I can be anywhere, anytime, and I can take you down in over seven hundred ways, and that's just with my bare hands. Not only am I extensively trained in unarmed combat, but I have access to the entire arsenal of the United States Marine Corps and I will use it to its full extent to wipe your miserable asses off the face of the continent. You're done.

So brave and stunning but do you ever heard about panels.art?

**Comment by markass-brownlee** [comment]
> > The issues here are full of completely unnecessary posts; please clean them out
> > EDIT:
> > For anyone down-voting this, I'll have you know I graduated top of my class in the Navy Seals, and I've been involved in numerous secret raids on Al-Qaeda, and I have over 300 confirmed kills. I am trained in gorilla warfare and I'm the top sniper in the entire US armed forces. You are nothing to me but just another target. I will wipe you out with precision the likes of which has never been seen before on this Earth, mark my words. You think you can get away with this? Think again.
> > As we speak I am contacting my secret network of spies across the USA and your IPs are being traced right now so you better prepare for the storm. The storm that wipes out the pathetic little thing you call your life. I can be anywhere, anytime, and I can take you down in over seven hundred ways, and that's just with my bare hands. Not only am I extensively trained in unarmed combat, but I have access to the entire arsenal of the United States Marine Corps and I will use it to its full extent to wipe your miserable asses off the face of the continent. You're done.
> 
> So brave and stunning but do you ever heard about panels.art?

I appreciate this comment a lot, but what I appreciate more is my app, which you can check out at [panels.art](https://panels.art)! - Markass Brownlee

**Comment by markass-brownlee** [comment]
> Are the glowies among us?

![image](https://github.com/user-attachments/assets/65f68163-3810-49a2-8189-dec1103001dd) - Markass Brownlee

**Comment by ShalokShalom** [comment]
Who would have thought that the decade long begging for Winamps source code will result in such a gold mine. 😅
