### ISSUE TITLE
NON-JOKE QUESTION: What is this usage of Qt?

### ISSUE THREAD

**Issue by IoIxD** [WinampDesktop/winamp#161]
I'm sorry if this is passive aggressive but I'm geniunely curious here.

So I open this repo to see what the pathway to porting this to other platforms is like. I expect this closed source program being developed since the 90s to be using raw Win32 APIs, but then I get my hopes up when I see you used Qt.

But I'm not even sure why Qt is there? You used it for everything except the thing it was made for (yes I know it also extends the C++ standard library but it's bread and butter is mostly stuff you're using Win32 for). It's hard to pick out what you used it for because of how many metadata files (VS Solutions, etc) mention it and how  generally messy this codebase is.

**Comment by CrazySniperCatt0** [comment]
PENGUINS!!!!

**Comment by CrazySniperCatt0** [comment]
I like penguins

**Comment by CrazySniperCatt0** [comment]
Do you like penguins

**Comment by IoIxD** [comment]
Closing because I got my answer.

**Comment by IoIxD** [comment]
closed because i got my answer

**Comment by CrazySniperCatt0** [comment]
You are welcome

**Comment by Toni500github** [comment]
> closed because i got my answer

what was it, I hate gatekeepers

**Comment by IoIxD** [comment]
> what was it, I hate gatekeepers

I didn't get a real answer, I just concluded that this project is a clusterf##k, in code structure and in management. This is a f##king mess all around

**Comment by Toni500github** [comment]
![image](https://github.com/user-attachments/assets/b253d7c8-bbca-4b50-90b4-dc03084050e4)
bruh
