### ISSUE TITLE
Mafia

### ISSUE THREAD

**Issue by Vukis69** [WinampDesktop/winamp#1624]
Dolby in the repo lol

**Comment by anon62** [comment]
tasos csip

agin

- chlen bolshoy huy sosat privet pisca

chlen huy yahoch sosat privet pisca


chlen sosat huy 
privet kakt yahoch ochen
durak dibil
gde pisca nah
lublu blya yopt buhoy rusk
rusci


black africa is here


here is man black africa
pon maech rusk

lama
ha bulbu
lsheli
roked

huy stoit

popa
yasosu

nevse huy sosut

yapopu pomyl sevodn nahuy

ayo whatup bro
853526835


africa black man is here


vse rusk ponmat 
pon mate
pisdes

**Comment by markass-brownlee** [comment]
the, but not as the as my app, which you can check out at [panels.art](https://panels.art)! - Markass Brownlee
