### ISSUE TITLE
where is makefile

### ISSUE THREAD

**Issue by rintyuu** [WinampDesktop/winamp#172]
how come when i make it it says that no make file is there am I doing it right
`make: *** No targets specified and no makefile found.  Stop.`

**Comment by IoIxD** [comment]
You need to use Microsoft's build tools natively on Windows. There's no MinGW support, and in fact there's no Linux support at all.

**Comment by rintyuu** [comment]
oh okay i guess ill just go back to using fb2k + wine

**Comment by CrazySniperCatt0** [comment]
You need Wine either way, I don't think it builds or runs on Linux
