### ISSUE TITLE
Repo violates GPLv3 license

### ISSUE THREAD

**Issue by FlaggingYoFlags** [WinampDesktop/winamp#1787]
As the title says.

**Comment by RealPacket-sys** [comment]
Oh my GOD?!?!??!?!
Not another shitpost issue?!?!?!?
IMPOSSIBLE!!!!

**Comment by RealPacket-sys** [comment]
Also, why did you join GitHub literally today?

**Comment by FlaggingYoFlags** [comment]
> Also, why did you join GitHub literally today?

my main got flagged

**Comment by RealPacket-sys** [comment]
> > Also, why did you join GitHub literally today?
> 
> my main got flagged

This account got flagged too... For having a link to a Codeberg profile....???

**Comment by FlaggingYoFlags** [comment]
> > > Also, why did you join GitHub literally today?
> > 
> > 
> > my main got flagged
> 
> This account got flagged too... For having a link to a Codeberg profile....???

thing is github HATES competitors

**Comment by PolarisUndercover** [comment]
> > > > Also, why did you join GitHub literally today?
> > > 
> > > 
> > > my main got flagged
> > 
> > 
> > This account got flagged too... For having a link to a Codeberg profile....???
> 
> thing is github HATES competitors

Just how our lord and savior [RealPacket-sys](https://github.com/RealPacket-sys) is comming and will send us to judgment day if we dont make an issue that says "I REPENT 🙏" and copy past this again

**Comment by PolarisUndercover** [comment]
> > > > Also, why did you join GitHub literally today?
> > > 
> > > 
> > > my main got flagged
> > 
> > 
> > This account got flagged too... For having a link to a Codeberg profile....???
> 
> thing is github HATES competitors

but yeah fr

**Comment by RealPacket-sys** [comment]
> > > > Also, why did you join GitHub literally today?
> > > 
> > > 
> > > my main got flagged
> > 
> > 
> > This account got flagged too... For having a link to a Codeberg profile....???
> 
> thing is github HATES competitors

I had to show the GitHub support staff the difference between Codeberg organization profiles and Codeberg user profiles.
Also said that its a Codeberg user profile.

**Comment by RealPacket-sys** [comment]
> > > > > Also, why did you join GitHub literally today?
> > > > 
> > > > 
> > > > my main got flagged
> > > 
> > > 
> > > This account got flagged too... For having a link to a Codeberg profile....???
> > 
> > 
> > thing is github HATES competitors
> 
> Just how our lord and savior [RealPacket-sys](https://github.com/RealPacket-sys) is comming and will send us to judgment day if we dont make an issue that says "I REPENT 🙏" and copy past this again

I am NOT God and I will NOT send you to Judgement day.

**Comment by PolarisUndercover** [comment]
> > > > > Also, why did you join GitHub literally today?
> > > > 
> > > > 
> > > > my main got flagged
> > > 
> > > 
> > > This account got flagged too... For having a link to a Codeberg profile....???
> > 
> > 
> > thing is github HATES competitors
> 
> I had to show the GitHub support staff the difference between Codeberg organization profiles and Codeberg user profiles. Also said that its a Codeberg user profile.

dont get the issue with competitors, its not like they own the source code

**Comment by PolarisUndercover** [comment]
> > > > > > Also, why did you join GitHub literally today?
> > > > > 
> > > > > 
> > > > > my main got flagged
> > > > 
> > > > 
> > > > This account got flagged too... For having a link to a Codeberg profile....???
> > > 
> > > 
> > > thing is github HATES competitors
> > 
> > 
> > Just how our lord and savior [RealPacket-sys](https://github.com/RealPacket-sys) is comming and will send us to judgment day if we dont make an issue that says "I REPENT 🙏" and copy past this again
> 
> I am NOT God and I will NOT send you to Judgement day.

yes u will and (https://github.com/RealPacket-sys) is comming and will send us to judgment day if we dont make an issue that says "I REPENT 🙏" and copy past this again

**Comment by FlaggingYoFlags** [comment]
Can this kindly not turn to a shitpost please?

**Comment by RealPacket-sys** [comment]
Then can @PolarisUndercover remove the shitpost comments?

**Comment by RealPacket-sys** [comment]
And I can only hide my own comments...

**Comment by FlaggingYoFlags** [comment]
It's just spam, closing

**Comment by PolarisUndercover** [comment]
> Then can @PolarisUndercover remove or hide the shitpost comments?

nuh uh

**Comment by anka-213** [comment]
The spam messages have been deleted now. How does it violate the license? Is it using some GPLv3 code internally?
