### ISSUE TITLE
Open Letter

### ISSUE THREAD

**Issue by FlaggingYoFlags** [WinampDesktop/winamp#1789]
Before you call this a shitpost, I wanna explain this. **This is not a shitpost. This is a completely unbiased open letter to the people in the issues tab.**

Now. Let's begin.

So you might notice there's this little shit who puts amen quotes bcoz some dood is actually doing his job for the winamp idiots that don't even do anything.

Now, for the amen person.. **Shut the fuck up, this isn't going to achieve anything.** All you're doing is clogging up the issues tab with unwanted comments about your little bunker cult just to stop the atheist devils.

Like come on, this has happened before but you're just whining like a little shit. You're not him.

I know that endings can be hard but I'd like to end it abruptly like we always do.

Fin!

**Comment by FlaggingYoFlags** [comment]
Anyone who likes to do **constructive** critism, please say it here.

**Comment by PolarisUndercover** [comment]
Theres like 900 other issues + the person maintaining it does not care about providing ANY support for this and just got the license as a cash grab, theyre not asociated with any of the og creators, they deliveratly uploaded it with a very restrictive license just for the advertising of having something as open source

**Comment by PolarisUndercover** [comment]
They literally leaked closed source code from Dolby and cert keys

**Comment by FlaggingYoFlags** [comment]
> Theres like 900 other issues + the person maintaining it does not care about providing ANY support for this and just got the license as a cash grab, theyre not asociated with any of the og creators, they deliveratly uploaded it with a very restrictive license just for the advertising of having something as open source

That doesn't explain why you decided to do this bullshit.

**Comment by FlaggingYoFlags** [comment]
> They literally leaked closed source code from Dolby and cert keys

Doesn't even explain too.

**Comment by PolarisUndercover** [comment]
> > Theres like 900 other issues + the person maintaining it does not care about providing ANY support for this and just got the license as a cash grab, theyre not asociated with any of the og creators, they deliveratly uploaded it with a very restrictive license just for the advertising of having something as open source
> 
> That doesn't explain why you decided to do this bullshit.

so the guy can stop caring about such a trivial issue and spend their time doing something more productive and rewarding than trying to salvage an obvious corporate scam project

**Comment by FlaggingYoFlags** [comment]
> > > Theres like 900 other issues + the person maintaining it does not care about providing ANY support for this and just got the license as a cash grab, theyre not asociated with any of the og creators, they deliveratly uploaded it with a very restrictive license just for the advertising of having something as open source
> > 
> > 
> > That doesn't explain why you decided to do this bullshit.
> 
> so the guy can stop caring about such a trivial issue and spend their time doing something more productive and rewarding than trying to salvage an obvious corporate scam project

Scam project? Wipe that up my asshole.

**Comment by FlaggingYoFlags** [comment]
Closing as this is not up for arguing.

**Comment by PolarisUndercover** [comment]
https://github.com/WinampDesktop/winamp/commit/68ec62b8cf51f596878fc42524288d8741a4540d

**Comment by PolarisUndercover** [comment]
read the license its clearly written in a way to make the minimum amount of effort

**Comment by RealPacket-sys** [comment]
> They literally leaked closed source code from Dolby and cert keys

No, leaking dolby source is good! Leak proprietary source code! Leak proprietary source code! Leak proprietary source code! Leak proprietary source code! Leak proprietary source code! Leak proprietary source code! Leak proprietary source code! Leak proprietary source code! Leak proprietary source code! Leak proprietary source code! Leak proprietary source code! Leak proprietary source code! Leak proprietary source code!

**Comment by Vukis69** [comment]
Dolby's code need to be shown to the world, show me all the spyware they created

**Comment by RealPacket-sys** [comment]
> Dolby's code need to be shown to the world, show me all the spyware they created

Yes.
