### ISSUE TITLE
add sex

### ISSUE THREAD

**Issue by norbcodes** [WinampDesktop/winamp#1914]
please add sex thx

**Comment by OctoBanon-Main** [comment]
![image](https://github.com/user-attachments/assets/0acb3bbe-7206-4c5f-b4e6-52678eee1886)

**Comment by norbcodes** [comment]
what about gay sex then

**Comment by LIZARD-OFFICIAL** [comment]
yes

**Comment by 0xA50C1A1** [comment]
> what about gay sex then

![Gachimuchi](https://github.com/user-attachments/assets/85871b62-08a1-4600-9705-4b3f46096b50)

**Comment by LIZARD-OFFICIAL** [comment]
> what about gay sex then

no

**Comment by norbcodes** [comment]
No sex guys

**Comment by arefdsg** [comment]
say gex

**Comment by LIZARD-OFFICIAL** [comment]
⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⣠⣰⣤⣴⣤⣤⣄⡀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀
⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⣄⣰⣶⣿⣿⣿⣿⣿⣿⣿⣷⣯⣿⣲⣤⡀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀
⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⢠⣴⣿⣿⣿⠿⢿⣿⣿⣿⣿⠩⢷⣈⣽⣿⣛⣿⡖⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀
⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⢠⣿⡿⢻⣿⣿⣦⡾⠛⣟⠛⠛⢻⠶⣿⠉⢹⠀⠉⣿⣤⣤⣄⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀
⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⢠⣿⡿⠃⠀⠈⠙⠓⣷⣀⠈⠐⢀⣾⠃⠉⠛⠛⠛⣶⠏⠀⠀⣌⡙⢦⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀
⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⢀⣿⣻⠁⠀⠀⠀⠀⠀⢈⣿⠳⠖⠛⠁⢠⣄⡀⠤⣴⡿⠀⠀⠀⠠⠽⡎⢷⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀
⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⢸⣟⡿⠀⠀⠀⠀⠀⠀⠀⠿⣤⣀⡀⠀⠀⠘⠛⠻⣛⣠⣤⠇⠀⠀⠀⢿⣸⡇⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀
⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⣿⣹⠇⠀⠀⠀⠀⠀⠀⠀⠀⠀⠈⠙⠛⠛⠛⠛⠛⠛⠋⠷⣮⠀⠀⠀⠈⣷⣧⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀
⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⢰⡿⣴⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠰⠀⠀⠀⠀⣠⡾⠋⠀⠀⠀⠀⢼⢸⡀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀
⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⢸⡇⣿⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⢰⣏⡀⠀⠀⠀⠀⠀⠸⣸⡇⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀
⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⢸⡇⡏⠀⠀⠀⠀⠀⠀⠀⠀⠀⢀⡀⠀⠀⠀⠀⠀⠀⣀⠠⠙⣷⠀⠀⠀⠀⠈⢼⡇⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀
⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⣸⣇⡇⠀⠀⠀⠀⠀⠀⠀⠀⠀⢸⡇⠀⠉⠶⢀⣼⠖⠃⢂⢡⣿⠀⠀⠀⠀⠀⢺⡇⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀
⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⢀⣼⠟⣿⡇⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠻⣶⣤⣤⡾⠛⠶⣦⠶⠟⠁⠀⠀⠀⠀⡀⢸⣇⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀
⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⣀⣠⡶⠞⢿⡀⠈⢿⣄⠄⠀⠀⠀⠀⠀⠀⠀⠀⠁⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⢀⣿⢹⣧⡀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀
⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⣠⡴⠟⠋⠈⠀⠀⠈⠻⣄⠀⠙⢳⣄⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⢀⡾⠃⣸⠇⠙⠓⢦⣄⠀⠀⠀⠀⠀⠀⠀⠀⠀
⠀⠀⠀⠀⠀⠀⠀⠀⣠⡴⠟⠁⡐⠀⠀⠀⠀⠀⠀⠀⠈⠳⣄⠀⠈⠳⢤⡀⠀⠉⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⣴⠟⠁⣰⠟⠀⠀⠀⠀⠈⠛⢦⣀⠀⠀⠀⠀⠀⠀
⠀⠀⠀⠀⠀⠀⣠⡾⠋⠀⠠⠉⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠈⠳⣄⡀⠀⠉⠳⢦⣄⡀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⢠⣴⠟⠁⢀⡼⠃⠀⠀⡀⠀⠀⠀⠀⠀⠙⢷⣤⣀⠀⠀⠀
⠀⠀⠀⠀⣠⣞⣋⣀⣀⣀⣀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠙⠶⣄⡀⠀⠈⠙⠛⠶⢤⣤⣀⠀⠀⠀⣀⣴⠛⠁⠀⣠⠞⠁⠀⠀⢸⡇⠀⠀⠀⠀⠀⠀⢠⡇⠈⣷⡀⠀
⠀⠀⣤⠾⠋⠉⠀⠀⠀⠀⠉⠉⠓⠶⣄⡀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠙⠳⢦⣄⡀⠀⠀⢀⣩⠿⠶⣾⠋⠙⠳⣤⡞⠁⠀⠀⠀⠀⠘⣧⠀⠀⠀⠀⠀⠀⠀⡇⠀⡏⣻⡄
⠀⣸⡿⠂⠀⠀⢀⣀⣀⣀⣀⠀⠀⠀⠀⠙⢦⡀⠀⠀⠀⣠⠀⠀⠀⠀⠀⠀⠀⠀⠀⠈⠉⠓⠶⣼⣇⠀⢠⣼⣧⠀⠀⠁⠀⠀⠀⠀⠀⠀⠀⠻⣆⠀⠀⠀⠀⢀⡼⠃⠀⠀⣿⠃
⢰⡟⢀⣤⠶⢻⡿⠋⠉⠈⠉⠉⠓⢦⡀⠀⠈⢳⡀⠀⣠⠟⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠈⠀⠀⠈⠉⠙⣧⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠹⣇⠀⣀⡤⠞⠁⠀⢀⡾⣿⠀
⠘⠻⣿⠇⣼⡟⠁⠀⠀⠀⠀⠀⠀⠲⣙⢦⡀⢀⢳⠾⠃⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠚⣷⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠘⢿⣉⢀⣀⣤⠞⠋⢀⣿⠀
⠀⠀⣿⣯⢸⠃⠀⠀⠀⠀⠀⠀⠀⠀⠘⢆⢳⡸⡿⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠠⣤⣼⣇⠀⢀⠀⠀⠀⠀⠀⠀⠀⠀⠈⢻⣏⠉⠀⠀⠀⢸⡇⠀
⠀⠀⢸⣿⣾⠁⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⢼⣷⠃⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠉⠫⠽⣿⡙⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⢻⣆⠀⠀⣠⣿⠁⠀
⠀⠀⠈⢻⣿⡇⠀⠙⠶⠀⠀⠀⠀⠀⠀⠀⠸⢼⡆⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠘⢷⡀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⢿⠀⠠⣿⠏⠀⠀
⠀⠀⠀⠨⢿⣧⣀⠤⠀⠀⠀⠀⠀⠀⠀⠀⠀⠞⣧⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠸⣇⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠸⡆⢠⡿⠀⠀⠀
⠀⠀⠀⠀⠈⢿⣿⠄⠘⠀⠀⠀⠀⠀⠀⠀⠀⢘⣻⡄⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⢀⣴⣿⡄⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⢿⠈⣿⠀⠀⠀
⠀⠀⠀⠀⠀⠀⣟⢷⡄⠀⠀⠀⠀⡀⠀⠀⠀⢸⣿⡇⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠈⠙⣇⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⢸⠋⣽⠂⠀⠀
⠀⠀⠀⠀⣾⣟⠛⠛⣛⣆⠀⠀⣼⡇⢀⠀⠀⠐⣻⡇⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⣿⠀⠀⠀⠀⠀⠀⠀⠀⠀⢀⣸⣷⡿⣶⠀⠀
⠀⠀⠀⠀⠙⠿⣧⣾⠛⠉⣿⡾⢿⣷⣸⣄⠀⢰⣹⡇⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⣿⠀⠀⠀⠀⠀⠀⠀⠀⠀⣴⠏⢽⣿⡟⠀⠀
⠀⠀⠀⠀⠀⠀⠀⣿⣆⢠⣿⠀⢸⡿⠀⠘⣦⡼⣽⠁⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠐⢾⣿⡏⠀⠀⠀⠀⠀⢀⣼⣳⣿⣿⢶⠾⠋⠀⠀⠀
⠀⠀⠀⠀⠀⠀⠀⢨⣿⣶⣿⣅⣺⣿⣀⠀⣸⣽⣇⡀⠀⠰⣄⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⢠⡟⠀⠀⠀⠀⣀⣴⣿⣿⣿⡗⠁⠀⠀⠀⠀⠀⠀
⠀⠀⠀⠀⠀⠀⠀⠘⢿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣷⣿⣷⣦⣤⣀⣀⠀⠓⢦⣄⣀⠀⠀⠀⠀⠀⠀⠀⠀⣀⣀⣤⠶⢿⣴⣶⣶⣶⣿⣿⣿⣿⣿⣻⠃⠀⠀⠀⠀⠀⠀⠀
⠀⠀⠀⠀⠀⠀⠀⠀⠈⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣷⣶⣶⣶⣾⠟⠉⢉⠠⢀⡿⣀⣿⣿⣿⣿⣿⣿⣿⣿⡏⠀⠀⠀⠀⠀⠀⠀⠀
⠀⠀⠀⠀⠀⠀⠀⠀⠀⠈⢿⣿⣿⣿⣿⣿⣽⣻⣟⡿⣿⢿⣿⣿⣿⣿⣿⣿⡿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣦⣤⣦⣤⣯⣶⣿⣿⣟⡿⣿⣿⣿⣿⡟⠀⠀⠀⠀⠀⠀⠀⠀⠀
⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠻⣿⣿⣿⣿⣯⢷⣿⣻⣽⣟⣾⣳⣟⣯⣟⣿⣽⣟⣿⣻⣟⣿⣻⣟⣿⣻⣟⡿⣿⢿⣻⡿⣟⣿⣯⢿⣯⣿⣿⣿⡿⠋⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀
⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠘⢿⣿⣿⣿⣻⣞⣿⣳⣯⣷⢿⣽⣾⣻⢾⣷⣻⡾⣷⣻⡾⣷⣻⡷⣿⣞⣿⡽⣟⣯⣿⣻⢿⣾⣻⣿⣿⣿⠟⠁⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀
⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⣿⣿⣿⣷⣻⣯⡷⣟⣾⣟⡷⣯⣟⡿⣞⣷⢿⣻⡽⣿⣽⡿⣽⣷⠿⣽⣻⢿⣽⣞⣯⣿⢾⣿⣿⣟⠁⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀
⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⢀⣿⣿⣿⡷⣯⣷⢿⣻⣽⡾⣿⡽⣯⢿⣻⣽⣟⣯⣿⢿⠾⣛⣩⣴⣿⣿⣻⢿⣞⣯⣿⣞⣿⣿⣿⡇⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀
⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⢸⣿⣿⣿⣟⣷⣻⣯⣟⣷⢿⣳⣿⣻⣟⣯⣷⣻⢯⣿⢸⣿⣿⢿⣻⣽⣾⣻⢯⣟⣯⣷⢿⣾⣿⣿⡇⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀
⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⢀⣿⣿⣿⣿⣻⣞⣯⣷⢿⡾⣟⣯⣷⢿⡽⣟⣾⡽⣟⣿⢸⣿⣯⢿⣯⣷⢯⣟⡿⣯⣟⣾⢿⣳⣿⣿⡇⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀
⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⢸⣿⣿⣿⣟⡷⣿⣽⡾⣿⡽⣿⣽⢾⣟⡿⣿⣽⣻⣟⣿⢸⣿⣯⢿⡾⣽⣻⣯⢿⣽⣾⣻⣟⡿⣿⣿⣷⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀
⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⣸⣿⣿⣿⣯⢿⣻⣾⣽⢷⣿⣻⢾⡿⣽⣻⣟⣾⢷⣻⣿⢸⣿⣯⣟⣿⡽⣷⣻⣯⣷⢯⣷⣟⣿⣿⣿⢻⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀
⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⣿⣿⣿⣿⣾⡟⣿⡞⣯⣿⡞⣿⡟⣿⣯⣷⣿⣯⣿⣽⣿⢸⣿⣷⢻⣾⢻⣽⢳⣿⣾⣿⣿⣾⣿⣿⣿⣽⡇⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀
⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⣿⣿⣿⣿⣞⣿⣳⣿⣻⣽⣻⢷⣟⣿⣾⣿⣿⣾⣿⣷⣿⢸⣿⣯⣟⣾⣿⣻⣿⣿⣿⣿⣿⣿⣿⣿⣿⣽⣓⢦⡄⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀
⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⢸⣿⣿⣿⣟⣾⣽⣳⣿⣳⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⡻⢿⣾⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣷⣝⢧⡀⠀⠀⠀⠀⠀⠀⠀⠀⠀
⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠈⣻⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣮⠻⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⡎⣷⠀⠀⠀⠀⠀⠀⠀⠀⠀
⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⡇⢻⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣧⡟⠀⠀⠀⠀⠀⠀⠀⠀⠀
⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠘⢿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣷⣼⠿⢿⣿⣿⣿⣿⣿⣿⣿⡿⠿⠿⠿⠿⠛⠛⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀
⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠉⠉⠛⠻⠿⠿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⡿⠿⠛⠉⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀
⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠉⠈⠁⠉⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀

**Comment by mineisstupid** [comment]
pls add sex
