### ISSUE TITLE
The license forbids forking, but people are forking the repo

### ISSUE THREAD

**Issue by ZaDarkSide** [WinampDesktop/winamp#20]
> Thankfully the License forbids people of forking and making copies of this repo, so no copies of the repo with the uploaded unmodified source tree exists :D

![image](https://github.com/user-attachments/assets/136e818a-c3dc-4148-9e0e-d6833e55f544)

The license is not working, should I make a new issue about the License not working ? I see forks but the license forbids them...impossibru

![image](https://github.com/user-attachments/assets/31b02213-360b-4d5f-8fb6-275c7ca83244)

_Originally posted by @ZaDarkSide in https://github.com/WinampDesktop/winamp/issues/17#issuecomment-2371982813_

**Comment by jfmauguit** [comment]
It's a duplicate, I'm closing it

**Comment by ZaDarkSide** [comment]
You are right it was, thanks.
