### ISSUE TITLE
signtool/codesign cert and password opted to be there?

### ISSUE THREAD

**Issue by abbbi** [WinampDesktop/winamp#22]
hi,

i havent tried (and i wont), but what it looks like, the signtool pfx file and password are part of the release, too:

 https://github.com/WinampDesktop/winamp/tree/community/Src/codesign
 https://github.com/WinampDesktop/winamp/blob/community/Src/codesign/sign.cmd#L5

Update: looks like the certificate is expired, according to:

https://github.com/WinampDesktop/winamp/blob/community/Src/codesign/Pi%C3%A8ce%20jointe%20sans%20titre%2000003.html
```
 Certificate Validity Start Date: 2022-06-10 
 Certificate Validity End Date: 2024-06-12 
```

**Comment by Yotsubal** [comment]
![image](https://github.com/user-attachments/assets/31f2ad3c-7087-4c4b-a2b8-820e1bd1b132)

**Comment by ZaDarkSide** [comment]
So if you want to digitally sign any binary to say it was digitally signed by Winamp SA it will work?

**Comment by Yotsubal** [comment]
Someone really messed up

**Comment by lgrn** [comment]
> So if you want to digitally sign any binary to say it was digitally signed by Winamp SA it will work?

Yes, if you also invent a time machine and travel back to June 11th of this year.

**Comment by ZaDarkSide** [comment]
> > So if you want to digitally sign any binary to say it was digitally signed by Winamp SA it will work?
> 
> Yes, if you also invent a time machine and travel back to June 11th of this year.

I can just set my PC clock way back, so no need to time travel 😉

**Comment by Yotsubal** [comment]
<img width="271" alt="{37D7CEF6-A40D-442D-A85F-57FA7CFCCAD4}" src="https://github.com/user-attachments/assets/7dae81ff-d5fc-4b5e-87a5-1f382f77db71">



> > So if you want to digitally sign any binary to say it was digitally signed by Winamp SA it will work?
> 
> Yes, if you also invent a time machine and travel back to June 11th of this year.
> 
> **edit** I'd be more concerned about the password and the possibility that it's been re-used for other purposes, because it doesn't look generated.

its June 12th

**Comment by jfmauguit** [comment]
Thanks, removed this expired code sign cert

**Comment by bibarub** [comment]
> expired

make sure to add new ones later

**Comment by matty45** [comment]
Well done helping the malware and video game cheat developers. .-.

**Comment by Lastorder-DC** [comment]
> > > So if you want to digitally sign any binary to say it was digitally signed by Winamp SA it will work?
> > 
> > 
> > Yes, if you also invent a time machine and travel back to June 11th of this year.
> 
> I can just set my PC clock way back, so no need to time travel 😉

for anyone thinks this will work, to prevent that there are `code signing timestamp` will make sure that timestamp is not tampered. 

so you really need time machine to use expired certs.

**Comment by ZaDarkSide** [comment]
> > > > So if you want to digitally sign any binary to say it was digitally signed by Winamp SA it will work?
> > > 
> > > 
> > > Yes, if you also invent a time machine and travel back to June 11th of this year.
> > 
> > 
> > I can just set my PC clock way back, so no need to time travel 😉
> 
> for anyone thinks this will work, to prevent that there are `code signing timestamp` will make sure that timestamp is not tampered.
> 
> so you really need time machine to use expired certs.

Okay genius, you didn't get the joke...yeah it was a joke, some people really take stuff too seriously, also most devs know how a certificate works, no point to explain how not setting the clock in the past will not work, but thanks for trying!
