### ISSUE TITLE
WCL Version 1.0.1

### ISSUE THREAD

**Issue by jakubtalich** [WinampDesktop/winamp#231]
This is a joke, right? For God's sake. At least hire a lawyer before some nerd publishes a custom license update. Thank you very much, indeed.

**Comment by jakubtalich** [comment]
Additional Qs: Anyway, can I at least get a confirmation from your license nerd who acts to have studied a law school that your company won't sue me if I break the license?

**Comment by ErdbeerbaerLP** [comment]
I don't think they try to be joking, sadly


> 
>   MIT License
> 
>   Copyright (c) 2024 ErdbeerbaerLP
> 
>   Permission is hereby granted, free of charge, to any person reading this comment, to deal with the comment without restriction, including without limitation the rights to use, copy, modify, merge, publish, distribute, sublicense, and/or sell copies of the comment, and to permit persons to whom the comment is furnished to do so, subject to the following conditions:
> 
>   The above copyright notice and this permission notice shall be included in all copies or substantial portions of the comment.
>   THE COMMENT IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE COMMENT OR THE USE OR OTHER DEALINGS IN THE COMMENT.
