### ISSUE TITLE
1098 issues opened by 275 people

### ISSUE THREAD

**Issue by 000yesnt** [WinampDesktop/winamp#2675]
According to the [project insights](https://github.com/WinampDesktop/winamp/pulse),
> 1098 Issues opened by 275 people
> 27 Pull requests opened by 26 people 
> 232 Issues closed by 50 people 

PS: Has anyone found anything interesting in the code yet?

**Comment by random-nonce** [comment]
1098 :nerd_face: :point_up:

**Comment by 000yesnt** [comment]
fuckign

**Comment by 000yesnt** [comment]
oh, 100 issues just vanished. are maintainers back?? yay!!!

**Comment by 000yesnt** [comment]
I can't delete this issue so I'm just going to close it
