### ISSUE TITLE
中华人民共和国真诚感谢您发布专有的杜比代码！中国加油! 🇨🇳

### ISSUE THREAD

**Issue by misandrie** [WinampDesktop/winamp#27]

**Comment by misandrie** [comment]
![image](https://github.com/user-attachments/assets/3c72c886-142b-420e-b54c-a2faa1c6d394)
![image](https://github.com/user-attachments/assets/1adbb579-f3cb-4c87-aa5b-6d4d4f0be8e6)

**Comment by cosmic-zip** [comment]
![2560px-thumbnail-2077456406](https://github.com/user-attachments/assets/8c007095-9c21-4943-8239-d85c5c1ec1c6)


https://www.youtube.com/watch?v=OjNpRbNdR7E
