### ISSUE TITLE
[Meta] The hell is going on?

### ISSUE THREAD

**Issue by theasin** [WinampDesktop/winamp#2835]
I recommend purging some of the recent issues as they may contain URLs to malicious resources

**Comment by dxgldotorg** [comment]
> I recommend purging some of the recent issues as they may contain URLs to malicious resources

Report the user posting them for abuse to GitHub.

**Comment by theasin** [comment]
> > I recommend purging some of the recent issues as they may contain URLs to malicious resources
> 
> Report the user posting them for abuse to GitHub.

Have done that, waiting for GitHub to take action

**Comment by ChristianIvarsson** [comment]
We'll probably have to wait til' Monday. Don't see much action during the weekends unless it's extremely severe.

Why can't they implement some sort of security level where you're not allowed to post issues unless you've had the account for a while? Most of these posts comes from newly created ones.

**Comment by Zorrototo** [comment]
All of that only shows how much these people don't care, it only hinders what could be achieved with this repo.
It is annoying because nothing will be done to revive Winamp properly and extend it.
I wish them all a good extended ban on their main account because not only are they obvious unintelligent troll, but they are also coward to hide behind newly created account.

**Comment by ChristianIvarsson** [comment]
> > it only hinders what could be achieved with this repo.
> 
> What could be achieved with this repo lol? If they didn't wanna seek attention with this POS license and actually wished to revive Winamp, you wouldn't see this bunch of kids spamming in the first place.
> 
> > All of that only shows how much these people don't care
> 
> Tell me who doesn't care. Llama Group who repeatedly shits on Winamp's reputation by shoving NFTs into it, baiting open source community into contributing to their proprietary crap they can take away any day?
> 
> Someone has to be very... "unintelligent" to contribute to this proprietary codebase. It does not benefit the community in any way whatsoever; quite the opposite in fact, given that they explicitly want you to lose all rights to your own contributions.

Cool story bro

**Comment by Eiji7** [comment]
@Zorrototo Not cowards, but stupid cowards. GitHub can locate them simply by their IP and even if they use VPN then there are still some possible ways especially if they broke law … VPN services gives anonymous only for normal people (like shopping privacy) and when you broke law then nobody wants to be **responsible** for you, so it's only about how much `winamp` team care and how good law system is in their country.

**Comment by TheRektafire** [comment]
"what the hell is going on" is basically that it seems like the winamp devs basically just dropped the code and ghosted everyone despite needing to make glaringly obvious changes to the repo and needing to put way more effort into moderation. I don't get how people are supposed to take them seriously and even want to contribute to begin with (even if the ridiculous license they have allowed you to do so which it technically doesn't despite supposedly being a "collaborative license"...) when they've been acting like this

**Comment by dxgldotorg** [comment]
It's possible that GitHub may be doing the bulk of the work at removing trolls.  Just had GitHub Support come back to me confirming two users were actioned on, in which case their entire accounts, repos and everything, were taken down.

**Comment by Zorrototo** [comment]
It is on us to report each individual account, especially the real one (in case of newly created I just focus on malicious content to waste less time). Let the idiots learn the lesson, report their account for Disruptive content.

**Comment by theasin** [comment]
Malicious issues got nuked
