### ISSUE TITLE
СТРАШНЕЙШИЙ ВИРУС В ИГРЕ ПРО ВИНАМП

### ISSUE THREAD

**Issue by EJYozhenka** [WinampDesktop/winamp#288]
в игре винамп ёжика был найден вирус, который сливает все ваши данные
смотрите фото
![ЕЖИНЫЙ КОМП ► Смешарики_ Компьютер Ёжика - YouTube - 0-1-17](https://github.com/user-attachments/assets/c1862602-205d-4c78-8072-f57559d13c5f)

**Comment by Laybox** [comment]
лучше уже не будет

**Comment by watermelon46** [comment]
ужас я обосрался 3000 раз не пугай так

**Comment by fleriane** [comment]
Wtf man is cool, winamp niggas

**Comment by shrklv** [comment]
о, я тебя узнал! это ты всякую дрисню слушал в винампе в 2006
