### ISSUE TITLE
Открытие чата поддержки Winamp

### ISSUE THREAD

**Issue by mxvslnch** [WinampDesktop/winamp#305]
Уважаемые пользователи,

Мы рады сообщить, что для улучшения качества обслуживания и оперативного решения ваших вопросов был создан официальный чат поддержки Winamp. Теперь вы можете напрямую обратиться к нашей команде, используя чат по ссылке: https://t.me/winamp_support

Наши специалисты готовы помочь вам с любыми техническими вопросами, проблемами, связанными с использованием приложения, а также предоставить актуальную информацию о функциях и обновлениях Winamp.

Мы ценим ваше доверие и надеемся, что новый формат поддержки позволит сделать ваше взаимодействие с Winamp еще более комфортным и эффективным.

С уважением,
Команда поддержки Winamp

**Comment by watermelon46** [comment]
Ты еблан?

**Comment by olo4eka** [comment]
ЛЕТС ФАКИНГ ГООО?

**Comment by mxvslnch** [comment]
> Ты еблан?

Здравствуйте,

Да, я являюсь так называемым "ебланом"
