### ISSUE TITLE
How To Contribute on Winamp Repository

### ISSUE THREAD

**Issue by Yotsubal** [WinampDesktop/winamp#35]
Due to the license terms which state: “_No Forking: You may not create, maintain, or distribute a forked version of the software,_” it is not possible to submit pull requests to this repository. Therefore, I’ve created this guide on how to contribute within these limitations.

According to the license, modifications are allowed strictly for private use: “_You are granted the right to modify the software for private use only_.” Consequently, the only viable option is to clone the repository or download the source code as a ZIP file, make the necessary changes locally, and proceed as follows:

**Submitting Your Changes**
Once you’ve made your changes, the next step is to create a new issue with the following format:

Issue Title: **[CHANGE REQUEST] Title of Your Change**
Issue Description: Provide a detailed list of the changes you made, including relevant file paths and line numbers.
Example:
```
1. Corrected a spelling mistake:
   https://github.com/WinampDesktop/winamp/blob/main/vcpkg_version_finder.py
   At line 20: print("the argumnets after the second one are ignored") -> print("the arguments after the second one are ignored")

2. Removed SHOUTcast source:
   https://github.com/WinampDesktop/winamp/tree/main/Src/Plugins/DSP/sc_serv3
```
Once the issue is submitted, wait for the maintainers to review and apply your proposed changes.

**Important:** _By submitting contributions through this process, you agree to assign all intellectual property rights, including copyright, in your contributions to Winamp, as stated in the license._

**Comment by Yotsubal** [comment]
~~Free labors~~

**Comment by 3doplayer67484** [comment]
> Due to the license terms which state: “_No Forking: You may not create, maintain, or distribute a forked version of the software,_” it is not possible to submit pull requests to this repository. Therefore, I’ve created this guide on how to contribute within these limitations.
> 
> According to the license, modifications are allowed strictly for private use: “_You are granted the right to modify the software for private use only_.” Consequently, the only viable option is to clone the repository or download the source code as a ZIP file, make the necessary changes locally, and proceed as follows:
> 
> **Submitting Your Changes** Once you’ve made your changes, the next step is to create a new issue with the following format:
> 
> Issue Title: **[CHANGE REQUEST] Title of Your Change** Issue Description: Provide a detailed list of the changes you made, including relevant file paths and line numbers. Example:
> 
> ```
> 1. Corrected a spelling mistake:
>    https://github.com/WinampDesktop/winamp/blob/main/vcpkg_version_finder.py
>    At line 20: print("the argumnets after the second one are ignored") -> print("the arguments after the second one are ignored")
> 
> 2. Removed SHOUTcast source:
>    https://github.com/WinampDesktop/winamp/tree/main/Src/Plugins/DSP/sc_serv3
> ```
> 
> Once the issue is submitted, wait for the maintainers to review and apply your proposed changes.
> 
> **Important:** _By submitting contributions through this process, you agree to assign all intellectual property rights, including copyright, in your contributions to Winamp, as stated in the license._

let me rewrite this in one sentence 

**Don't and you can't** 

<strike>just wait for foobar2000 to go open or use qmmp instead lmao</strike>

**Comment by Yotsubal** [comment]
> > Due to the license terms which state: “_No Forking: You may not create, maintain, or distribute a forked version of the software,_” it is not possible to submit pull requests to this repository. Therefore, I’ve created this guide on how to contribute within these limitations.
> > According to the license, modifications are allowed strictly for private use: “_You are granted the right to modify the software for private use only_.” Consequently, the only viable option is to clone the repository or download the source code as a ZIP file, make the necessary changes locally, and proceed as follows:
> > **Submitting Your Changes** Once you’ve made your changes, the next step is to create a new issue with the following format:
> > Issue Title: **[CHANGE REQUEST] Title of Your Change** Issue Description: Provide a detailed list of the changes you made, including relevant file paths and line numbers. Example:
> > ```
> > 1. Corrected a spelling mistake:
> >    https://github.com/WinampDesktop/winamp/blob/main/vcpkg_version_finder.py
> >    At line 20: print("the argumnets after the second one are ignored") -> print("the arguments after the second one are ignored")
> > 
> > 2. Removed SHOUTcast source:
> >    https://github.com/WinampDesktop/winamp/tree/main/Src/Plugins/DSP/sc_serv3
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > Once the issue is submitted, wait for the maintainers to review and apply your proposed changes.
> > **Important:** _By submitting contributions through this process, you agree to assign all intellectual property rights, including copyright, in your contributions to Winamp, as stated in the license._
> 
> let me rewrite this in one sentence
> 
> **Don't and you can't**
> 
> just wait for foobar2000 to go open or use qmmp instead lmao

~~This issue is a joke lol, not actual guide~~
