### ISSUE TITLE
ПОЧЕМУ ПРИ ВОИСПРЕВЕДЕНИЯ ЛЮБЫХ АУДИО ИГРАЕТ КОЛЯ КОЛЯ???

### ISSUE THREAD

**Issue by oladik666** [WinampDesktop/winamp#695]
Я НЕ ЕБАНУТЫЙ
ВОТ ПРУФЫ

https://github.com/user-attachments/assets/9ad01682-91b8-4347-83e5-b83bd2191788

**Comment by zonerkin** [comment]
чтобы жизнь мёдом не казалась

**Comment by TYMA22389** [comment]
это потому что разрабы ебланы уходим в винанп
